### ISSUE TITLE
Singularity image specification: can't pull nfcore-rnaseq-1.4.img Permission denied

### ISSUE THREAD

**Issue by kviljoen** [ewels/nf-core-rnaseq#21]
Hi Phil,

Is nfcore-rnaseq-1.4.img different from ngi-rnaseq-1.4.img? I currently only have the latter on our system as specified in the 'uct_hex' profile under file path /scratch/DB/bio/singularity-containers.

When trying to run the nextflow pipeline with:

```bash
/opt/exp_soft/cbio/nextflow/nextflow run \
  ewels/nf-core-RNAseq \
  --reads '/researchdata/fhgfs/katie/NGI-RNAseq-test/*_R{1,2}.fastq.gz' \
  --genome GRCh37 \
  --outdir /researchdata/fhgfs/katie/NGI-RNAseq-test/nextflow-output \
  -profile uct_hex \
  --email katie.viljoen@uct.ac.za \
  -with-singularity /scratch/DB/bio/singularity-containers/ngi-rnaseq.img
```

I have issues finding the specified input files and get: 

```
WARNING: Non existant bind point (directory) in container: '/researchdata
```

Might this have something to do with the singularity image? Should we rather define dynamically as described under your documentation with the `$wf_container` parameter? I've tried specifying in a custom config file using:

```groovy
process {
  container = {"docker://$wf_container"}
} 
```

But get authentication error:

```
Session aborted -- Cause: java.lang.IllegalStateException: Failed to pull singularity image
  command: singularity pull --name [-].img docker://[:] > /dev/null
  status : 1
  message:
    ERROR Authentication error, exiting.
```

**Comment by kviljoen** [comment]
Just an update (and more info) on this:
I've tried to pull nfcore-rnaseq-1.4.img but get an authentication error. The second problem (when running the pipeline with ngi-rnaseq-1.4.img might be similar to this previous issue?
https://github.com/SciLifeLab/NGI-RNAseq/issues/174

So I guess my main question is - is this something we need to be able to configure on our side by setting user defined bind points or should it work with nfcore-rnaseq-1.4.img or if you update the docker image as in issue 174

Thanks!

**Comment by ewels** [comment]
Hi @kviljoen,

Sorry for the lack of response - grant deadlines over here so a bit snowed under. I got as far as reformatting your initial post a little to make it easier to read before, hope that was ok.

Speed thoughts:

1) `ewels/nf-core-RNAseq` is my development fork. It's better to use `nf-core/RNAseq`
    * Just at the moment, the default `master` branch here is not a stable release (due to change soon hopefully). So you probably want to use `nextflow run nf-core/RNAseq -r dev` to use the development branch just at the moment as this has the most up to date code.
2) The error `WARNING: Non existant bind point (directory) in container:` sounds like a singularity error (not nextflow or pipeline) and probably has to do with the way Singularity is installed on your system. See the docs here: http://singularity.lbl.gov/docs-mount
    * In short, you want to have singularity installed with singularity overlays enabled. This isn't always possible if you're running on an old version of Linux. Without this, containers have to have disk mount points _within the container_ which makes generic images really difficult to create - we have to add the directory names of every cluster to the image.
   * If you can't have overlays enabled, you'll have to make your own version of the container (`FROM nfcore/rnaseq`) and add the bind points that you need manually. This is far from ideal.
3) `$wf_container` etc - as the above error is singularity and not nextflow, I'm afraid that there's nothing that we can do in the pipeline which will solve the error.
    * The authentication error you see is because the container name is now undefined and so you're trying to pull a singularity container called `docker://[:]`, which doesn't exist
4) We've completely rewritten the docker container since https://github.com/SciLifeLab/NGI-RNAseq/issues/174, so I'd be surprised if there are the same problems. It was a long issue though so I could be wrong!

Phil

**Comment by kviljoen** [comment]
Thanks for the response Phil. I was using your developement fork because nf-core/RNAseq doesn't have the uct_hex config. I can't pull the nfcore-rnaseq-1.4.img singularity image due to authentication error but I can pull ngi-rnaseq-1.4.img - is this perhaps a setting on your side? I am checking in the meantime if we can have overlays enabled.

Thanks.

**Comment by kviljoen** [comment]
Apparently overlays are only available for kernel 3.18 or higher and unfortunately we have < 3.18 on our cluster currently. So we will have to make our own version of the container..

**Comment by ewels** [comment]
> I was using your developement fork because nf-core/RNAseq doesn't have the uct_hex config.

Ah yes, it's not on the default `master` branch sorry - it's on the `dev` branch: https://github.com/nf-core/RNAseq/tree/dev (see `-r dev` comment above).

>  I can't pull the nfcore-rnaseq-1.4.img singularity image due to authentication error

This isn't an authentication problem or anything to do with the image itself. See the command that's in the log:

```
singularity pull --name [-].img docker://[:] > /dev/null
```

This should be:

```
singularity pull --name nfcore-rnaseq-1.4.img docker://nfcore/rnaseq > /dev/null
```

So there's something going wrong in the nextflow pipeline code here which is making `process.container` `null`. My guess is that this is because you've overwriting this variable in your config file - `$wf_container` has been removed from the pipeline fairly recently (apologies if it's not yet been removed from the docs). You shouldn't need to define `process.container` yourself anywhere.

> Apparently overlays are only available for kernel 3.18 or higher and unfortunately we have < 3.18 on our cluster currently. So we will have to make our own version of the container..

Ah, this is a shame. Sorry - there's not much that we can do from our side on this. Let me know if you need any pointers.

Phil

**Comment by kviljoen** [comment]
Hi Phil, 

Thanks for this and sorry for all the back and forth. The error I get when I do singularity pull as you've specified above:
`singularity pull --name nfcore-rnaseq-1.4.img docker://nfcore/rnaseq > /dev/null
ERROR  : Could not open image nfcore-rnaseq-1.4.img: Permission denied
ABORT  : Retval = 255`
I've deleted all custom config files so really not sure why this isn't working but ngi-rnaseq works fine

**Comment by ewels** [comment]
Ah ok, sorry I was going off your original post. That's super weird. What version of singularity are you using?

**Comment by ewels** [comment]
(I just double checked and that command works fine for me)

**Comment by ewels** [comment]
Closing due to lack of inactivity - please open a new issue on the main nf-core/rnaseq repo if you still have problems :)
